### PR TITLE
Multicloud GitOps: Cluster must have dynamic persistent storage

### PR DESCRIPTION
**Pull request by RyanMillerC**
Tried this pattern today on a cluster without persistent storage. Vault hung in a *Pending* state waiting for a PV to be created. This adds the requirement for anyone else who comes along.

### CODE REVIEW

**Comment by day0hero** [comment]
@RyanMillerC - What provider were you deploying on?

**Comment by RyanMillerC** [comment]
Testing things out on bare metal SNO. Worked great after I added dynamic storage

**Comment by day0hero** [comment]
okay awesome! I figured as much but didn't want to assume and be wrong. 

Can you run `make test` in your branch. This will run the spellcheck and linter against your repo and will help with the integration testing. 

Thanks for your contributions!

**Comment by mbaldessari** [comment]
Thanks @RyanMillerC this is great feedback. I'll merge as is and fix up the linting/spellchecker bits on top

**Pull request merged**
