### PR TITLE
Align format for Industrial Edge Pattern to publish on Portfolio Architecture center

### PR DESCRIPTION
**Pull request by rubyyyyang**
Images for proposed changes on industrial edge pattern that aligns the format with the content on Portfolio Architectures

### CODE REVIEW

**Comment by rubyyyyang** [comment]
Restored from accident delete. Commits to the format and images that align the Industrial Edge Pattern to Portfolio Architecture Center.

**Comment by mbaldessari** [comment]
This one has conflicts with the tip of the branch, so can't be merged as is

**Comment by rubyyyyang** [comment]
Thank you @mbaldessari for your response. I've resolved the conflict. Please check it again.

**Comment by mbaldessari** [comment]
Thanks, merging. I'll fix up the CI failures with a PR on top

**Pull request merged**
