### PR TITLE
List dependencies as step 1 for multicloud-gitops

### PR DESCRIPTION
**Pull request by RyanMillerC**
I tried to run the multicluster-gitops pattern on my machine today. The initial run failed because I didn't have the `ansible-playbook` command available. I was browsing other patterns and noticed the list on the Multicluster DevSecOps page. Adding it here so others can immediately see what tools are required.

(Not 100% that list is right for this pattern but it seems close)

### CODE REVIEW

**Review by day0hero — CHANGES_REQUESTED** [review]
@RyanMillerC - Could you please remove `sed`, and `jq` from this list. Otherwise, I'm good with it.

**Comment by mbaldessari** [comment]
sed is required by common/Makefile so it's good. I don't think `jq` is needed though. This will also fix https://github.com/hybrid-cloud-patterns/docs/issues/88. Although in our docs/ reorg, we should eventually split it out in a separate file that can be referenced by all patterns. If you drop `jq` and rebase against latest docs, it should all be green

Thanks!

**Comment by RyanMillerC** [comment]
Dropped `jq`. 👍

**Review by day0hero — APPROVED** [review]
/lgtm

**Pull request merged**
